# PyTorch Fundamentals

## Manipulating Tensors

In [36]:
import torch

In [37]:
x = torch.tensor([[1,2]]) # one entity of 2 items
y = torch.tensor([[1],[2]]) # 2 entities of 1 item each

In [38]:
print(x.shape)

torch.Size([1, 2])


In [39]:
print(y.shape)

torch.Size([2, 1])


In [49]:
x = torch.tensor([1,2])

In [50]:
x.shape

torch.Size([2])

In [62]:
x.unsqueeze(1).shape

torch.Size([2, 1])

In [40]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
torch.zeros((3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
torch.zeros((3,4)) == torch.zeros([3,4])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [43]:
torch.equal(torch.zeros((3,4)) , torch.zeros([3,4]))

True

In [44]:
x.dtype

torch.int64

In [45]:
x

tensor([[1, 2]])

In [46]:
x.shape

torch.Size([1, 2])

In [47]:
x.view(2,1)

tensor([[1],
        [2]])

In [ ]:
x.squeeze(1)

tensor([[1, 2]])

In [ ]:
x.squeeze(1).shape

torch.Size([1, 2])

In [63]:
x = torch.arange(25)

In [66]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [65]:
x.shape

torch.Size([25])

In [71]:
x.view(5,5)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [78]:
x.unsqueeze(1)

tensor([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]])

In [82]:
x.max()

tensor(24)

In [83]:
x = torch.rand([2,2])

In [84]:
y= torch.rand([2,2])

In [85]:
x

tensor([[0.2500, 0.7363],
        [0.9577, 0.8382]])

In [86]:
y

tensor([[0.4020, 0.7096],
        [0.8201, 0.8147]])

In [87]:
x+y

tensor([[0.6520, 1.4459],
        [1.7778, 1.6529]])

## Gradient

In [89]:
x = torch.tensor([[2.,-1.],[1.,1.]], requires_grad=True)

In [90]:
output = x.pow(2).sum()

In [91]:
output

tensor(7., grad_fn=<SumBackward0>)

In [92]:
output.backward()

In [93]:
x.grad

tensor([[ 4., -2.],
        [ 2.,  2.]])

In [94]:
torch.cuda.is_available()

False